FROM ubuntu:22.04

# Install dependencies
RUN apt-get -qq update && apt-get -qq install -y --no-install-recommends git zlib1g-dev ca-certificates libpng-dev libzip-dev libicu-dev zip unzip default-mysql-client cron

# Set up cron
RUN touch /var/log/cron.log

# Install AWS CLI
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
RUN unzip awscliv2.zip
RUN ./aws/install

# Install Hugo
RUN apt-get -qq install -y --no-install-recommends hugo


